name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  lint:
    name: Run PDK Validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: lint
      uses: jpogran/pdk-github-action@master
      with:
        list: true
